### PR TITLE
Add question type checked by JavaScript functions

### PR DESCRIPTION
**Pull request by seragunn**
Sample usage

```html
<script src="/js/permutations.js"></script>
<script>
    function checkCycles(ans) {
        return (input) => {
            const ans_perm = new Permutation(ans);
            const in_perm = new Permutation().parseCycles(input);
            return in_perm.equals(ans_perm);
        }
    } 
    function checkShuffle(ans) {
        return (input) => {
            const ans_perm = new Permutation(ans);
            const in_perm = new Permutation().parseList(input);
            return in_perm.equals(ans_perm);
        }
    } 
</script>
```

```julia
using QuizQuestions

scriptq("checkCycles([2, 12, 3, 5, 4, 9, 8, 7, 6, 10, 1, 11])")

scriptq("checkShuffle([[1,8,12],[2,3,6,7,9],[4,10,11]])")
```

### CODE REVIEW

**Comment by jverzani** [comment]
I was wondering how one injects a javascript snippet into the resulting HTML. You have this in your example:

"""
```javascript
// in JavaScript
function threshold(t) {
    return (input) => {
        return input >= threshold;
    }
}
```
"""

Would there be an easy `quarto` equivalent?

If not, would some "question" form be useful with a `show` method that writes out the `javascript` code for mime-type `text/html` be useful?

I'm thinking something like:

```
struct Script{T} <: ???
txt::T
end

script(txt) = Script(txt)
function Base.show(io::IO, ::MIME"text/html", s::Script) 
println(io, "<script>")
println(io, s.txt) # ? escaped?
println(io, "</script>")
end
```

Maybe this isn't needed, but it might be helpful?

**Comment by seragunn** [comment]
In Quarto you can put the script tags right into the file. I wouldn't try to have Julia try to programmatically output JavaScript that seems messy. The goal here is we have some external JavaScript code (for my current project, that's JavaScript code to represent permutations as cycles, lists, do multiplication, etc.). Plus that way you get syntax highlighting and debugging.

**Comment by seragunn** [comment]
Hold on, I think I rebased this branch on older commits...

**Comment by seragunn** [comment]
Yes, so other than Quarto which lets you write `<script>` tags right into the markdown, you might need some kind of show method to output those tags.

However, I don't know who would be planning on using that. I'm only planning on using this for Quarto and I'm not sure how many other people use this package (or if they're using it outside of Quarto).

**Comment by jverzani** [comment]
This looks great. I'll merge tomorrow and tag a new version unless you say hold off a bit. Thanks!

**Pull request merged**
